CREATE TABLE IF NOT EXISTS login_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin',
    evaluator_employee_id INTEGER,
    active INTEGER NOT NULL DEFAULT 1,
    last_login_at TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_login_users_username_lower ON login_users (LOWER(username));
CREATE INDEX IF NOT EXISTS idx_login_users_active ON login_users(active, username);

CREATE TABLE IF NOT EXISTS employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sector TEXT NOT NULL,
    role TEXT NOT NULL,
    hire_date TEXT NOT NULL DEFAULT '',
    monitor_start_date TEXT NOT NULL DEFAULT '',
    leadership_start_date TEXT NOT NULL DEFAULT '',
    termination_date TEXT NOT NULL DEFAULT '',
    is_monitor INTEGER NOT NULL DEFAULT 0,
    is_leadership INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    deactivated_at TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    created_by_user_id INTEGER,
    created_by_username TEXT NOT NULL DEFAULT '',
    updated_by_user_id INTEGER,
    updated_by_username TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL DEFAULT ''
);

ALTER TABLE employees ADD COLUMN IF NOT EXISTS hire_date TEXT NOT NULL DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS monitor_start_date TEXT NOT NULL DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS leadership_start_date TEXT NOT NULL DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS termination_date TEXT NOT NULL DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS is_leadership INTEGER NOT NULL DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS deactivated_at TEXT NOT NULL DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS created_by_user_id INTEGER;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS created_by_username TEXT NOT NULL DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS updated_by_user_id INTEGER;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS updated_by_username TEXT NOT NULL DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS updated_at TEXT NOT NULL DEFAULT '';

ALTER TABLE login_users ADD COLUMN IF NOT EXISTS evaluator_employee_id INTEGER;
CREATE INDEX IF NOT EXISTS idx_login_users_evaluator_employee ON login_users(evaluator_employee_id);

CREATE TABLE IF NOT EXISTS weekly_evaluations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    week_start TEXT NOT NULL,
    evaluator TEXT,
    notes TEXT,
    assiduidade_pct REAL NOT NULL DEFAULT 100,
    qualidade_pct REAL NOT NULL DEFAULT 100,
    taxa_erros_pct REAL NOT NULL DEFAULT 100,
    produtividade_pct REAL NOT NULL DEFAULT 100,
    comportamento_pct REAL NOT NULL DEFAULT 100,
    efficiency_pct REAL NOT NULL DEFAULT 100,
    items_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    assiduidade_just TEXT NOT NULL DEFAULT '',
    qualidade_just TEXT NOT NULL DEFAULT '',
    taxa_erros_just TEXT NOT NULL DEFAULT '',
    produtividade_just TEXT NOT NULL DEFAULT '',
    comportamento_just TEXT NOT NULL DEFAULT '',
    UNIQUE(employee_id, week_start)
);

ALTER TABLE weekly_evaluations ADD COLUMN IF NOT EXISTS efficiency_pct REAL NOT NULL DEFAULT 100;
ALTER TABLE weekly_evaluations ADD COLUMN IF NOT EXISTS items_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE weekly_evaluations ADD COLUMN IF NOT EXISTS assiduidade_just TEXT NOT NULL DEFAULT '';
ALTER TABLE weekly_evaluations ADD COLUMN IF NOT EXISTS qualidade_just TEXT NOT NULL DEFAULT '';
ALTER TABLE weekly_evaluations ADD COLUMN IF NOT EXISTS taxa_erros_just TEXT NOT NULL DEFAULT '';
ALTER TABLE weekly_evaluations ADD COLUMN IF NOT EXISTS produtividade_just TEXT NOT NULL DEFAULT '';
ALTER TABLE weekly_evaluations ADD COLUMN IF NOT EXISTS comportamento_just TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS monitor_monthly_evaluations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    month TEXT NOT NULL,
    evaluator TEXT,
    notes TEXT,
    acomp_metas_pct REAL NOT NULL DEFAULT 100,
    org_fluxo_pct REAL NOT NULL DEFAULT 100,
    suporte_equipe_pct REAL NOT NULL DEFAULT 100,
    disciplina_oper_pct REAL NOT NULL DEFAULT 100,
    created_at TEXT NOT NULL,
    acomp_metas_just TEXT NOT NULL DEFAULT '',
    org_fluxo_just TEXT NOT NULL DEFAULT '',
    suporte_equipe_just TEXT NOT NULL DEFAULT '',
    disciplina_oper_just TEXT NOT NULL DEFAULT '',
    UNIQUE(employee_id, month)
);

ALTER TABLE monitor_monthly_evaluations ADD COLUMN IF NOT EXISTS acomp_metas_just TEXT NOT NULL DEFAULT '';
ALTER TABLE monitor_monthly_evaluations ADD COLUMN IF NOT EXISTS org_fluxo_just TEXT NOT NULL DEFAULT '';
ALTER TABLE monitor_monthly_evaluations ADD COLUMN IF NOT EXISTS suporte_equipe_just TEXT NOT NULL DEFAULT '';
ALTER TABLE monitor_monthly_evaluations ADD COLUMN IF NOT EXISTS disciplina_oper_just TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS weekly_errors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    week_start TEXT NOT NULL,
    role_snapshot TEXT NOT NULL,
    error_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    qty INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    created_at TEXT NOT NULL
);

UPDATE employees
SET termination_date = substring(deactivated_at from 1 for 10)
WHERE active = 0
  AND COALESCE(termination_date, '') = ''
  AND COALESCE(deactivated_at, '') <> '';

UPDATE employees
SET is_monitor = 0,
    monitor_start_date = ''
WHERE COALESCE(is_leadership, 0) = 1
  AND COALESCE(is_monitor, 0) = 1;

UPDATE employees
SET active = 0,
    deactivated_at = CASE
        WHEN COALESCE(deactivated_at, '') = '' THEN now()::timestamp(0)::text
        ELSE deactivated_at
    END
WHERE COALESCE(termination_date, '') <> ''
  AND termination_date <= current_date::text
  AND active <> 0;

UPDATE employees
SET active = 1,
    deactivated_at = ''
WHERE COALESCE(termination_date, '') <> ''
  AND termination_date > current_date::text
  AND active <> 1;

CREATE INDEX IF NOT EXISTS idx_employees_active_role ON employees(active, is_leadership, sector, role, name);
CREATE INDEX IF NOT EXISTS idx_weekly_eval_employee_week ON weekly_evaluations(employee_id, week_start);
CREATE INDEX IF NOT EXISTS idx_weekly_eval_employee_week_desc ON weekly_evaluations(employee_id, week_start DESC);
CREATE INDEX IF NOT EXISTS idx_weekly_errors_employee_week ON weekly_errors(employee_id, week_start);
CREATE INDEX IF NOT EXISTS idx_monitor_eval_employee_month ON monitor_monthly_evaluations(employee_id, month);

ALTER TABLE login_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_errors ENABLE ROW LEVEL SECURITY;
ALTER TABLE monitor_monthly_evaluations ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
    login_users,
    employees,
    weekly_evaluations,
    weekly_errors,
    monitor_monthly_evaluations
FROM anon, authenticated;
