CREATE TABLE IF NOT EXISTS bonus_adjustments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    week_start TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    description TEXT NOT NULL,
    created_at TEXT NOT NULL,
    created_by_user_id INTEGER REFERENCES login_users(id) ON DELETE SET NULL,
    created_by_username TEXT NOT NULL DEFAULT '',
    CONSTRAINT bonus_adjustments_amount_nonzero CHECK (amount <> 0),
    CONSTRAINT bonus_adjustments_amount_limit CHECK (abs(amount) <= 100000),
    CONSTRAINT bonus_adjustments_description_length CHECK (char_length(trim(description)) BETWEEN 3 AND 240),
    CONSTRAINT bonus_adjustments_week_format CHECK (week_start ~ '^\d{4}-\d{2}-\d{2}$')
);

CREATE INDEX IF NOT EXISTS idx_bonus_adjustments_employee_week
ON bonus_adjustments(employee_id, week_start);

CREATE INDEX IF NOT EXISTS idx_bonus_adjustments_week_employee
ON bonus_adjustments(week_start, employee_id);

ALTER TABLE bonus_adjustments ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE bonus_adjustments FROM anon, authenticated;
